package com.cmap.comm.enums;

public enum ScriptType {

	BACKUP,
	RESTORE_WITH_COPY_CONFIG,
	RESTORE_WITHOUT_COPY_CONFIG,
	VM_INFO,
	VM_SUBSCRIBERS,
	VM_POWER_OFF,
	VM_POWER_ON,
	VM_SHUTDOWN_PORT,
	CLUSTER_STATUS,
	CLUSTER_MIGRATE,
	SERVICE_RESTART
}
